### ISSUE TITLE
SyntaxError: Unexpected token const

### ISSUE THREAD

**Issue by mantoni** [zeke/jus#27]
Hi,

I just installed `jus` as per the homepage instruction. When I run `jus`, I get

```
/usr/local/lib/node_modules/jus/cli.js:16
if (args._[1]) const sourceDir = path.resolve(process.cwd(), args._[1])
               ^^^^^
SyntaxError: Unexpected token const
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3
```

That's on node v6.2.0.

I guess the problem is that `const` is used within an if-statement.

**Comment by zeke** [comment]
Weird. Lemme give it a try.
